-- ************************************* SqlDBM: Snowflake ************************************
-- * Generated by SqlDBM: TestAutotestProject+14540, v2 vs v1 by alexey.litvinenko@sqldbm.com *

CREATE TABLE table_7
(

);