-- **************************************** SqlDBM: Snowflake ***************************************
-- * Generated by SqlDBM: Snowflake SampleDb0, v2 vs v1 by vladislav+standart_enterprise@sqldbm.com *

CREATE TABLE table_7
(

);