-- *********************************** SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Snowflake SampleDb0, v31 vs v30 by a4vlad4a+enterprise@gmail.com *

ALTER TABLE table_16
    ADD COLUMN a_1  NOT NULL;