-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** order_coupons_view
CREATE VIEW order_coupons_view AS
  SELECT
    orders.order_id,
    orders.customer_id,
    coupons.code,
    coupons.discount,
    coupons.start_date,
    coupons.end_date
  FROM orders
  JOIN order_coupons
    ON orders.order_id = order_coupons.order_id
  JOIN coupons
    ON order_coupons.coupon_id = coupons.coupon_id;
