-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** view_2
CREATE VIEW view_2
  Comment = 'No Comment Provided'
AS
(
  -- Please type View Definition here
);
