-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** addresses
CREATE TABLE addresses
(
 address_id     int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 customer_id    int NOT NULL,
 address_line_1 varchar(255) NOT NULL,
 address_line_2 varchar(255) NOT NULL,
 city           varchar(255) NOT NULL,
 state          varchar(255) NOT NULL,
 zip_code       varchar(255) NOT NULL,
 country        varchar(255) NOT NULL
);
