-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *

-- ************************************** customers
CREATE TABLE customers
(
 customer_id   int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 first_name    varchar(255) NOT NULL,
 last_name     varchar(255) NOT NULL,
 email         varchar(255) NOT NULL,
 password      varchar(255) NOT NULL,
 creation_date timestamp_ltz NOT NULL
);
