-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *

-- ************************************** order_coupons
CREATE TABLE order_coupons
(
 order_coupon_id int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 order_id        int NOT NULL,
 coupon_id       int NOT NULL
);
