-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** order_items
CREATE TABLE order_items
(
 order_item_id int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 order_id      int NOT NULL,
 product_id    int NOT NULL,
 quantity      int NOT NULL
);
