-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *

-- ************************************** orders
CREATE TABLE orders
(
 order_id    int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 customer_id int NOT NULL,
 order_date  timestamp_ltz NOT NULL
);
