-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** products
CREATE TABLE products
(
 product_id  int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 name        varchar(255) NOT NULL,
 description varchar(10000) NOT NULL,
 price       numeric(10,2) NOT NULL,
 image_url   varchar(255) NOT NULL,
 in_stock    int NOT NULL
);
