-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *

-- ************************************** product_reviews
CREATE TABLE product_reviews
(
 review_id   int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 customer_id int NOT NULL,
 product_id  int NOT NULL,
 rating      int NOT NULL,
 review      varchar(10000) NOT NULL,
 review_date timestamp_ltz NOT NULL
);
