-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** table_16
CREATE TABLE table_16
(
 a    NOT NULL,
 a_1  NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( a )
);
