-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *
-- ************************************** TABLEWITHCLUSTER_copy_1
CREATE TRANSIENT TABLE TABLEWITHCLUSTER_copy_1
(
 A number(38,0),
 B number(38,0)
)
CLUSTER BY ( A );
