-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Snowflake SampleDb0 by a4vlad4a+enterprise@gmail.com *

-- ************************************** wishlists
CREATE TABLE wishlists
(
 wishlist_id int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 customer_id int NOT NULL,
 product_id  int NOT NULL
);
